### ISSUE TITLE
希望增加支持tag规则

### ISSUE THREAD

**Issue by abel533** [AliyunContainerService/image-syncer#10]
tag规则可以类似harbor：
![image](https://user-images.githubusercontent.com/1787798/69403071-a1aab080-0d34-11ea-8fe3-735d995e753b.png)

主要想自动同步最新（按时间）的一个版本。

**Comment by imdingtalk** [comment]
这个，确实很有用，希望可以有

**Comment by willzhang** [comment]
确实很需要啊，我的github action 为了同步calico 镜像已经跑了一个半小时了还没跑完，太多无用tag了

**Comment by zw999** [comment]
同楼上，非常需要

**Comment by willzhang** [comment]
skopeo支持，可以作为可选项

**Comment by smallhorsegg** [comment]
23年了   真希望支持

**Comment by hhyasdf** [comment]
支持正则匹配理论是可行的，但是如果是希望支持用时间信息来判断是否同步镜像，比较困难，因为每个公有的镜像服务 list tag 的 api 都不相同，对接起来比较困难

**Comment by hhyasdf** [comment]
最新的 v1.5.2 版本支持了以正则表达式匹配 tag，“按照时间同步tag” 的功能描述跟另一个 issue #52 重复了，这个 issue 会先被 close 掉，在另一个 issue 里跟进。
