### ISSUE TITLE
unsupported manifest type: application/vnd.oci.image.manifest.v1+json

### ISSUE THREAD

**Issue by denverdino** [AliyunContainerService/image-syncer#100]
Bug Report
---

Type: *bug report*

### What happened

I got such error when syncing knative images from gcr.io

ERRO[2022-06-02 15:30:19] Get blob info from gcr.io/knative-releases/knative.dev/client/cmd/kn:sha256-7954fe11a6dce1ec92f77355f2d8438dc39a0e34195e294becb9f70631397ca3.sbom error: unsupported manifest type: application/vnd.oci.image.manifest.v1+json

### Environment
- image-syncer version:
- OS (e.g. `cat /etc/os-release`):
- Registry version (e.g. `habor`):
- Others:

**Comment by denverdino** [comment]
In  pkg/sync/manifest.go

Add following code snippet

```
       } else if t == v1.MediaTypeImageManifest {
		manifestInfo, err := manifest.OCI1FromManifest(m)
		if err != nil {
			return nil, err
		}
		manifestInfoSlice = append(manifestInfoSlice, manifestInfo)
		return manifestInfoSlice, nil
	}
	
```

**Comment by huapox** [comment]
+1

**Comment by huapox** [comment]
```bash
INFO[2023-02-01 17:43:03] Get manifest from registry.hub.docker.com/library/ubuntu:20.04
ERRO[2023-02-01 17:43:03] Get manifest info from registry.hub.docker.com/library/ubuntu:20.04 error: unsupported manifest type: application/vnd.oci.image.index.v1+jsonStart to retry sync tasks, please wait ...
INFO[2023-02-01 17:43:03] Get manifest from registry.hub.docker.com/library/ubuntu:20.04
ERRO[2023-02-01 17:43:03] Get manifest info from registry.hub.docker.com/library/ubuntu:20.04 error: unsupported manifest type: application/vnd.oci.image.index.v1+json
Finished, 1 sync tasks failed, 0 tasks generate failed
```

**Comment by lingdie** [comment]
+1

**Comment by huapox** [comment]
- https://github.com/opencontainers/image-spec/blob/main/manifest.md
- https://github.com/opencontainers/image-spec/blob/main/media-types.md

**Comment by htlabc** [comment]
我已经解决了这个问题，晚点提个pr上来

**Comment by htlabc** [comment]
> * https://github.com/opencontainers/image-spec/blob/main/manifest.md
> * https://github.com/opencontainers/image-spec/blob/main/media-types.md

我已经解决了这个问题，晚点提个pr上来

**Comment by lujiajing1126** [comment]
Done in https://github.com/AliyunContainerService/image-syncer/pull/112
