### ISSUE TITLE
希望增加registry/repository格式的同步

### ISSUE THREAD

**Issue by imdingtalk** [AliyunContainerService/image-syncer#11]
我们现在的仓库格式，使用前任留下来的，格式是registry/repository ； 已经在生产了，不太好改动。
现在的格式必须严格要求registry/namespace/repository这样的格式，希望没有namespace的方式也能支持，谢谢。

例如：
目前严格要求的格式： "docker.io/exampleNamespace/image:v1.1.1":"harbor.io/exampleNamespace/image:v1.1.1" 
希望也支持这种格式：
"docker.io/image:v1.1.1":"harbor.io/image:v1.1.1"

**Comment by imdingtalk** [comment]
另外，同步速度真的是太快了~

**Comment by imdingtalk** [comment]
额~ 大家都没这个需求么~

**Comment by hhyasdf** [comment]
由于发现这个情况普遍存在，在v1.0.5版本中已经添加这个支持，可以看下issue #30 哈～

**Comment by imdingtalk** [comment]
> 由于发现这个情况普遍存在，在v1.0.5版本中已经添加这个支持，可以看下issue #30 哈～

感谢感谢，非常感谢
