### ISSUE TITLE
增量同步问题

### ISSUE THREAD

**Issue by imdingtalk** [AliyunContainerService/image-syncer#12]
对于增量同步，当前的判断依据是blob信息。在正常情况下没有问题；如果远端删除了镜像，或者镜像被清理则会出现问题。如图，
![image](https://user-images.githubusercontent.com/16778873/69477440-6639e000-0e21-11ea-8f08-5a341470c0c8.png)

**Comment by hhyasdf** [comment]
感谢你的反馈！

不知道远端删除镜像的具体场景是什么？增量同步一般是建立在原来同步的基础上进行的，如果进行了一次同步之后，目标（destination）仓库删除了已同步过的镜像，然后需要用原来的同步配置文件继续同步，是否意味着这个镜像不应该被删除？:) 这个时候已同步过的镜像层信息（records文件）已经失效，可以直接删除，这样会重新进行一次全量同步

同样，如果修改或者使用了新的同步配置文件，并且不是只添加或者只删除了同步规则，而是进行了规则的替换，考虑到这并不是传统意义上增量的场景，而应该是在一个新的同步上下文中，这种情况下推荐使用--records指定一个新records文件路径哈～（如果确定原来的records文件已经无效，也可以删除）

或者你有更好的意见，也欢迎提出，我们可以对此进行讨论～

**Comment by imdingtalk** [comment]
> 感谢你的反馈！
> 
> 不知道远端删除镜像的具体场景是什么？增量同步一般是建立在原来同步的基础上进行的，如果进行了一次同步之后，目标（destination）仓库删除了已同步过的镜像，然后需要用原来的同步配置文件继续同步，是否意味着这个镜像不应该被删除？:) 这个时候已同步过的镜像层信息（records文件）已经失效，可以直接删除，这样会重新进行一次全量同步
> 
> 同样，如果修改或者使用了新的同步配置文件，并且不是只添加或者只删除了同步规则，而是进行了规则的替换，考虑到这并不是传统意义上增量的场景，而应该是在一个新的同步上下文中，这种情况下推荐使用--records指定一个新records文件路径哈～（如果确定原来的records文件已经无效，也可以删除）
> 
> 或者你有更好的意见，也欢迎提出，我们可以对此进行讨论～

场景的话，我只是在测试该工具的 增量 同步的效果的时候，尝试删除了目标仓库的镜像；不过典型场景的增量同步这个目前是实现得很好的。。。 实际上我可能就是想确认同步到目标仓库的镜像没有问题（ps:   因为同步速度太快，让人难以置信，O(∩_∩)O ）

**Comment by hhyasdf** [comment]
O(∩_∩)O 很高兴这个工具能帮到你，这个issue就先关闭了哈～，如果有问题可以再打开它
