### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by lztly** [AliyunContainerService/image-syncer#142]
Bug Report
---

Type: *bug report*

###
Occasionally the following error will appear

panic: close of closed channel

### Environment
- image-syncer version: 1.5.2
- OS (e.g. `cat /etc/os-release`): CentOS 7
- Registry version (e.g. `habor`): Jfrog
- Others:

**Comment by hhyasdf** [comment]
Thanks for your reporting!

Please check if it's fixed in v1.5.4 :D.
