### ISSUE TITLE
image-syncer是否可以支持不同账户的并发上传？

### ISSUE THREAD

**Issue by lanyyyy** [AliyunContainerService/image-syncer#15]
hello：
    如果现在有2个不同的账户，需要将一个image推送到不同的registry里，这两个账户间的上传，可以并发执行么？

**Comment by hhyasdf** [comment]
这个是支持的哈

**Comment by lanyyyy** [comment]
好，多谢，我测试一下   ：）

**Comment by imdingtalk** [comment]
配置文件里面直接指定不同的registry的认证信息~  这个README里面有说明的呀
