### ISSUE TITLE
这个可以设置http-proxy么？

### ISSUE THREAD

**Issue by lanyyyy** [AliyunContainerService/image-syncer#16]

**Comment by hhyasdf** [comment]
工具本身现在不支持设置http_proxy，推荐借助proxychains这类工具实现代理哈～

**Comment by lanyyyy** [comment]
OK，那就是也是可以通过这种方式实现proxy代理上传？   这个我测试一下，多谢

**Comment by hhyasdf** [comment]
嗯嗯，有问题可以随时交流哈～

**Comment by jiusanzhou** [comment]
Golang的标准库 \`net/http\` 是实现了从环境变量读取代理配置的
