### ISSUE TITLE
toomanyrequests : ... tasks have been processed

### ISSUE THREAD

**Issue by ytanck** [AliyunContainerService/image-syncer#160]
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit. Now 2/2 tasks have been processed

**Comment by SoldierFace** [comment]
This might help:This file might fix it
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by ytanck** [comment]
错误日志：
time="2024-09-19 10:34:22" level=error msg="Failed to executed generating sync tasks from docker.io/library/nginx:1.13 to registry.cn-beijing.aliyuncs.com/yt-mirror/nginx:1.13: generate docker.io/library/nginx:1.13 image source error: reading manifest 1.13 in docker.io/library/nginx: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit. Now 1/1 tasks have been processed."

**Comment by imdingtalk** [comment]
dockerhub很明确地告诉你受限了，，你在这里反馈有啥用
