### ISSUE TITLE
manifest invalid: Invalid image, fail to parse 'manifest.json'

### ISSUE THREAD

**Issue by nineaiyu** [AliyunContainerService/image-syncer#163]
使用命令，同步dockerhub 到华为云，遇到异常，blob层同步成功，但是 manifest 却失败了
---

Type: *bug report*
![image](https://github.com/user-attachments/assets/0d412734-9283-412d-87fe-94397e1b3b29)

```
ERRO[2024-11-16 15:48:36] Failed to executed synchronizing manifest from docker.io/nineaiyu/xadmin-web:4.2.1 to swr.cn-north-4.myhuaweicloud.com/nineaiyu/xadmin-web:4.2.1: failed to put manifest: uploading manifest 4.2.1 to swr.cn-north-4.myhuaweicloud.com/nineaiyu/xadmin-web: manifest invalid: Invalid image, fail to parse 'manifest.json'. Now 1/1 tasks have been processed. 
```

### Environment
- image-syncer version:  v1.5.5
- OS (e.g. `cat /etc/os-release`): CentOS Stream 8
- Registry version (e.g. `habor`):
- Others:

**Comment by nineaiyu** [comment]
已经确定问题，
![image](https://github.com/user-attachments/assets/ae4a82f6-8e8d-4693-b099-768f9972ec73)

**Comment by zackzhangkai** [comment]
问题+1
