### ISSUE TITLE
manifest blob unknown: blob unknown to registry

### ISSUE THREAD

**Issue by silentred** [AliyunContainerService/image-syncer#23]
This error happens a lot. It seems most blob has been upload to target registry, because when I manually push the image to registry, it will be completed very fast.

**Comment by hhyasdf** [comment]
It will be more appreciated if you can provide more information (e.g., what kind of registry, version of registry, your operations, logs of image-syncer, etc.)

But I'm wondering if you are using an origin Docker Registry? This kind of registry maybe need some special settings before starting it. And we are seeking help from community for this as well[#7](https://github.com/AliyunContainerService/image-syncer/issues/7).
