### ISSUE TITLE
支持使用子用户或是AccessKeyId登录吗？

### ISSUE THREAD

**Issue by wajika** [AliyunContainerService/image-syncer#24]
另外出现这个提示image destination error: invalid reference format 之前是否可以做个判断，显示出错的具体问题？

**Comment by hhyasdf** [comment]
目前不支持非docker username/password的方式登录哈～，image destination error: invalid reference format 的报错因为是底层库的报错，不是很好判断；能否提供你这边错误的配置内容参考下？

**Comment by wajika** [comment]
@hhyasdf 是我操作失误导致image destination error: invalid reference format 出现，原因应该是没有取到资源。
