### ISSUE TITLE
support config via yaml format

### ISSUE THREAD

**Issue by ruruiye** [AliyunContainerService/image-syncer#28]
yaml has better comment and readability. and it's just another format to write json.

**Comment by liangyuanpeng** [comment]
我认为当前阶段配置内容比较少,更重要的工作应该是稳定性和丰富的特性, yaml格式的支持似乎作用不大,当然了,如果你能贡献你的代码那就太好了

**Comment by hhyasdf** [comment]
This has been done in v1.2.0. Reopen it if you still have problems.
