### ISSUE TITLE
manifest list is not supported right now

### ISSUE THREAD

**Issue by zhangyoufu** [AliyunContainerService/image-syncer#32]
> manifest list is not supported right now

或可通过修改 github.com/containers/image/manifest.DefaultRequestedManifestMIMETypes 暂时规避

**Comment by liangyuanpeng** [comment]
是的 我也遇到了这个问题  目前有新进度吗

**Comment by hhyasdf** [comment]
manifest list 不支持的原因在于，manifest list 类型的镜像列表会需要将 list 中的所有镜像全部预先同步完成，这部分需要解析 manifest list 的内容，并且自动同步镜像，目前看来生产环境中 manifest list 使用场景并不多，暂时没有计划支持

可以考虑自动同步镜像之后手动创建 manifest list

**Comment by zhangyoufu** [comment]
Docker Hub 上 library/ 都是 manifest list 类型，现在无法使用 image-syncer 同步这些镜像。
既然短期内没有支持 manifest list 的打算，可以在 Accept: 头部明确这一点，获取普通的 v2 manifest。

**Comment by hhyasdf** [comment]
> Docker Hub 上 library/ 都是 manifest list 类型，现在无法使用 image-syncer 同步这些镜像。
> 既然短期内没有支持 manifest list 的打算，可以在 Accept: 头部明确这一点，获取普通的 v2 manifest。

好的，多谢建议，我理解现在的处理方式中，当获取到一个 manifest list 类型的 manifest 时，会明确显示不支持 manifest list，并显示错误，效果是一样的，并且能提供明确的信息

**Comment by liangyuanpeng** [comment]
@hhyasdf  你好，我现在正在尝试同步manifest list 类型的镜像，有什么信息可以帮助一下我吗？

例如，当我拿到manifests后应该如何处理？我对这部分不太熟悉，如果可以帮助我提供一下方向那就太好了!  

谢谢！

**Comment by hhyasdf** [comment]
> @hhyasdf 你好，我现在正在尝试同步manifest list 类型的镜像，有什么信息可以帮助一下我吗？
> 
> 例如，当我拿到manifests后应该如何处理？我对这部分不太熟悉，如果可以帮助我提供一下方向那就太好了!
> 
> 谢谢！

我理解，可以先用 image-syncer 将除了 manifest list 的 tag 全部同步过去，然后手动 docker pull/push 一下 manifest list 类型的镜像应该就行了哈～

**Comment by liangyuanpeng** [comment]
好吧，我也只是希望得到一个可以使用的镜像，并不需要多架构.例如镜像：``k8s.gcr.io/kube-proxy:v1.18.0``  

@hhyasdf   你们目前如果遇到manifest list的镜像是如何解决的？还是说当前还没遇到过这样的场景？  

我可以想到的一个方案是 修改image-syncer源码，将manifest list的镜像写入到一个文件,例如``json文件``,然后再在go中调用docker cli去pull镜像以及push镜像. 

如果有更好的建议非常欢迎与我分享. 谢谢！

**Comment by hulucc** [comment]
啊这。。

**Comment by jiusanzhou** [comment]
当前不支持可以先覆盖掉  `github.com/containers/image/manifest` 中的 `DefaultRequestedManifestMIMETypes`:

```go

func init() {
	manifest.DefaultRequestedManifestMIMETypes = []string{
		imgspecv1.MediaTypeImageManifest,
		manifest.DockerV2Schema2MediaType,
		manifest.DockerV2Schema1SignedMediaType,
		manifest.DockerV2Schema1MediaType,
		// manifest.DockerV2ListMediaType,
	}
}
```

**Comment by gzzchh** [comment]
有一个解决方案，先更新依赖containers/image到v5。
然后添加一个处理Scheme2List的方法，遍历这个List，找出需要的Arch对应的摘要，然后调用一次GetManifest获取该摘要的信息，接下来当作Schema2处理就好了。  
代码在这里。  
https://github.com/gzzchh/image-syncer/blob/master/pkg/sync/manifest.go

写得不好，所以就不提pr了

**Comment by willzhang** [comment]
故意不支持dockerhub的吧，是怕阿里云镜像仓库撑不住吗

**Comment by hulucc** [comment]
https://github.com/ivanilves/lstags 先用这个代替了

**Comment by mj520** [comment]
公开镜像 指定tag 是否可以支持不需要 manifest list 进行同步

**Comment by liulangwa** [comment]
可以看下我的pr
@gzzchh 感谢

**Comment by hhyasdf** [comment]
This has been supported by latest version v1.3.0, hope you like it!
