### ISSUE TITLE
想获取进度条有没有什么方案

### ISSUE THREAD

**Issue by felix0080** [AliyunContainerService/image-syncer#33]
想获取进度条有没有什么方案 @denverdino

**Comment by haobibo** [comment]
+1

When pushing images, the output/terminal sometimes halts for 10min+ and has no output, which leads to the failure of CI/CD service. Example: https://travis-ci.com/github/QPod/operation/jobs/347496168

**Comment by liulangwa** [comment]
可以自己实现

**Comment by hhyasdf** [comment]
1.5.0 版本会打印进度信息，以 task 完成数量的形式
