### ISSUE TITLE
Split config file to hide sensitive information 

### ISSUE THREAD

**Issue by zryfish** [AliyunContainerService/image-syncer#40]
Currently config file holds all the things, authentication, sync rules. It's unsafe to keep all things together. We had an issue when we want to store sync rules in Github repo, make it public to all of our team members, since `config.file` contains sensitive information, it's impossible to do that. I suggest split config file into `auth.json` and `images.json`, in a such way, we can publish sync rules without leaking any secret information.

**Comment by hhyasdf** [comment]
It's included after v1.2.0, thanks for your contribution again!
