### ISSUE TITLE
支持以harbor的项目维度进行同步吗

### ISSUE THREAD

**Issue by zhangzhenyu2** [AliyunContainerService/image-syncer#43]
支持以harbor的项目维度进行同步吗，不然每出现一个新镜像名都要同步改下配置。

**Comment by hhyasdf** [comment]
目前不支持，image-sycner 暂时没有对接 harbor 的接口以及逻辑，而从 docker registry http v2 的 api 来看，没有项目的概念～

**Comment by hhyasdf** [comment]
Just reopen it if you still have other questions.
