### ISSUE TITLE
better support for multiple destination

### ISSUE THREAD

**Issue by haobibo** [AliyunContainerService/image-syncer#45]
Currently, the `images` in the configuration is defined as a map.

When users `need to synchronize images from one source to multi destinations`, it is expected to `add more rules`.

However, for the cases for one source to multiple destinations, one key cannot be mapped to multiple values. So how about:

### A. use a list of key-values instead of to represent (source, destination) tasks, or
```json
{
  "images": [
    ["ubuntu:latest", "registry.cn-beijing.aliyuncs.com/something/ubuntu"],
    ["ubuntu:latest", "registry.us-west-1.aliyuncs.com/something/ubuntu"]
  ]
}
```
###  B. make the destination value in ImageList from string to list of values which represent multiple registries

```json
{
  "images": {
    "ubuntu:latest": [
      "registry.cn-beijing.aliyuncs.com/something/ubuntu",
      "registry.us-west-1.aliyuncs.com/something/ubuntu"
    ]
  }
}
```
### C. remain the current schema, but for the destination value in ImageList, allow users to use `,` to split multiple registries

```json
{
  "images": {
    "ubuntu:latest": "registry.cn-beijing.aliyuncs.com/something/ubuntu,registry.us-west-1.aliyuncs.com/something/ubuntu"
  }
}
```

**Comment by haobibo** [comment]
@hhyasdf  any plan/comments for this?

**Comment by hhyasdf** [comment]
> @hhyasdf any plan/comments for this?

Great advices!

We do have a plan for this which need to keep backward compatible.

**Comment by haobibo** [comment]
Great! Looking forward to trying that new feature.

**Comment by hhyasdf** [comment]
This is supported for v1.5.1. Please check the README for usage.
