### ISSUE TITLE
可否直接从源仓库v2接口读取全部镜像信息然后同步给目标库？

### ISSUE THREAD

**Issue by chldong** [AliyunContainerService/image-syncer#48]
配置文件直接读取源库https://xxx.xxx.xxx/v2

**Comment by hhyasdf** [comment]
直接读取主要问题在于权限，需要用 /v2/_catalog 的 docker http api 去 list 所有仓库，但是一般 harbor 以及 公有云 上，用户都不只一个，全量 list 镜像仓库的（所有用户的）所有 repository，不是非常合适的行为～

**Comment by hhyasdf** [comment]
Just reopen it if you still have other questions.
