### ISSUE TITLE
同步docker hub官方镜像会失败，提示命名空间错误

### ISSUE THREAD

**Issue by MSG-maniac** [AliyunContainerService/image-syncer#50]
{
    "auth": {
        "hub.docker.com": {
            "username": "xx",
            "password": "xxx"
        },
        "registry.cn-beijing.aliyuncs.com": {
            "username": "xxxxx",
            "password": "xxxx"
        }
    },
    "images": {
        "hub.docker.com/_/mysql": "registry.cn-beijing.aliyuncs.com/xxx/xxxx"
    }
}

 error: generate hub.docker.com/_/mysql image source error: invalid reference format 
Start to retry to generate sync tasks, please wait ...

**Comment by hhyasdf** [comment]
Is "hub.docker.com/_/mysql" your real repository name?

Command like `docker pull hub.docker.com/_/mysql` will fail cause of the same reason:
`invalid reference format`

**Comment by MSG-maniac** [comment]
"images": {
"mysql": "registry.cn-beijing.aliyuncs.com/xxx/xxxx"
}
这样即可，建议增加到FAQ里

**Comment by MSG-maniac** [comment]
Get blob info from registry.hub.docker.com/library/mysql:8.0 error: manifest list is not supported right now

**Comment by MSG-maniac** [comment]
拉取mysql时候会提示 manifest不支持

**Comment by hhyasdf** [comment]
Duplicated with #32
