### ISSUE TITLE
Hi!是否支持本地harbor同步局域网内docker registry，后同步至阿里ACR

### ISSUE THREAD

**Issue by haerr** [AliyunContainerService/image-syncer#51]
局域网内多个开发有不同docker registry，需要统一同步至本地harbor仓库后，再同步至阿里ACK ，期待您的回复！

**Comment by hhyasdf** [comment]
我理解是可以的，只要每个 registry 都支持，然后多次同步就好了哈～

**Comment by hhyasdf** [comment]
我理解是可以的，只要每个 registry 都支持，然后多次同步就好了哈～

**Comment by hhyasdf** [comment]
我理解是可以的，只要每个 registry 都支持，然后多次同步就好了哈～

**Comment by hhyasdf** [comment]
Just reopen it if you still have other questions.
