### ISSUE TITLE
command error

### ISSUE THREAD

**Issue by XLoren** [AliyunContainerService/image-syncer#56]
[root@n1 image-syncer]# ./image-syncer  --registry=xx.xx.com --namespace=ebg  --log=./log
Error: init sync client error: Generate confg error: unmarshal config error: invalid character '?' after object key:value pair
Usage:
  image-syncer [flags]

Aliases:
  image-syncer, image-syncer

Flags:
      --config string      config file path (default "/root/image-syncer/image-syncer.json")
  -h, --help               help for image-syncer
      --log string         log file path (default in os.Stderr)
      --namespace string   default destinate namespace when destinate namespace is not given in the config file, can also be set with DEFAULT_NAMESPACE environment value
  -p, --proc int           numbers of working goroutines (default 5)
      --records string     records file path, to record the blobs that have been synced, auto generated if not exist (default "/root/image-syncer/records")
      --registry string    default destinate registry url when destinate registry is not given in the config file, can also be set with DEFAULT_REGISTRY environment value
  -r, --retries int        times to retry failed task (default 2)

init sync client error: Generate confg error: unmarshal config error: invalid character '?' after object key:value pair

**Comment by XLoren** [comment]
参照着文档进行操作，执行同步时候，报了这个错误。image-syncer.json也做了配置

**Comment by hhyasdf** [comment]
It's just a json format error, please check your image-syncer.json, for the "invalid character '?'"

**Comment by XLoren** [comment]
我重新json格式化了一下，解决了
