### ISSUE TITLE
目的仓库没有相应repo时，不会主动创建repo吗？

### ISSUE THREAD

**Issue by tbag2011** [AliyunContainerService/image-syncer#60]
如题

**Comment by hhyasdf** [comment]
这个取决于对应目标仓库的行为，可以看下同步的目标仓库是否有相关设置，比如阿里云 ACR 可以进行如下配置：
![image](https://user-images.githubusercontent.com/16648891/103724831-3becb700-5010-11eb-93ae-7fe4e9136496.png)

**Comment by tbag2011** [comment]
harbor好像没有这个功能欸，需要手动去创建才行，不然会报requested access to the resource is denied错误

**Comment by hhyasdf** [comment]
> harbor好像没有这个功能欸，需要手动去创建才行，不然会报requested access to the resource is denied错误

嗯嗯，看了下，harbor 仓库作为目标仓库的话，应该是需要创建下对应的仓库的～
