### ISSUE TITLE
不能正常使用

### ISSUE THREAD

**Issue by tokyo2006** [AliyunContainerService/image-syncer#61]
系统 MacOS:11.1
输入命令 image-syncer -h
`zsh: exec format error: image-syncer`

**Comment by hhyasdf** [comment]
macos 需要自己编译下哈～
![image](https://user-images.githubusercontent.com/16648891/104705137-8084fa80-5754-11eb-9dd0-330ef0469a90.png)

**Comment by hhyasdf** [comment]
参考：https://github.com/AliyunContainerService/image-syncer#compile-manually
