### ISSUE TITLE
是否支持同步GCR镜像到ACR

### ISSUE THREAD

**Issue by tokyo2006** [AliyunContainerService/image-syncer#63]
- 如题，是否支持GCR同步镜像到ACR

GCR的auth配置不是简单的密码，包含了很多东西，不知道image-syncer是否能支持GCR的同步工作

**Comment by hhyasdf** [comment]
参考下 https://cloud.google.com/container-registry/docs/advanced-authentication，看下是否可行哈～

**Comment by hhyasdf** [comment]
> * 如题，是否支持GCR同步镜像到ACR
> 
> GCR的auth配置不是简单的密码，包含了很多东西，不知道image-syncer是否能支持GCR的同步工作

参考下这个文档看下是否可行哈～，只要能够生成 docker login 的账号密码就行，https://cloud.google.com/container-registry/docs/advanced-authentication

**Comment by gzroy** [comment]
试了一下，是可以的，需要用到Google cloud的Access token的方式，把token作为密码，不过这个token只有60分钟的有效期
