### ISSUE TITLE
可否支持按照digest来同步镜像

### ISSUE THREAD

**Issue by gzroy** [AliyunContainerService/image-syncer#65]
现在需要定义源镜像为tag的方式，是否可以支持以digest的方式来定义？

**Comment by hhyasdf** [comment]
目前同步单个镜像层的场景比较有限，可以先看下什么时候会有这个场景

**Comment by gzroy** [comment]
@hhyasdf ,我现在想同步kubeflow的镜像到阿里云，但是里面有一些镜像是以digest的方式来拉取的，如果image-syncer能支持digest的方式就完美了。

**Comment by willzhang** [comment]
确实很需要啊，我的github action 为了同步calico 镜像已经跑了一个半小时了还没跑完，太多无用tag了

**Comment by hhyasdf** [comment]
1.5.0 版本已经支持这个功能
