### ISSUE TITLE
images里面有一部分没有同步

### ISSUE THREAD

**Issue by lovitus** [AliyunContainerService/image-syncer#66]
程序使用的json配置文件
images段内有以下的配置
1,原有的dockerHub->dockerHub
2,追加:dockerHub->阿里镜像服务
运行后,实际运行后只同步 到阿里. 原来的配置没有任何效果, 日志里没有任何相关记录, 日志最后的统计失败,也是显示无失败.

**Comment by hhyasdf** [comment]
在 json 的语法里，一个 map 的 key 只能对应一个 value，如果是配置文件中一个 key 对应了多个 value 的话，则只会同步后面 key 的镜像，前面的规则会被覆盖

**Comment by hhyasdf** [comment]
这种情况可以考虑先拆分成两个配置文件进行两次同步

**Comment by lovitus** [comment]
> 在 json 的语法里，一个 map 的 key 只能对应一个 value，如果是配置文件中一个 key 对应了多个 value 的话，则只会同步后面 key 的镜像，前面的规则会被覆盖
> 
> 相同的镜像如果要一对多同步目前可以考虑这样：
> 
> 1,原有的dockerHub->新的dockerHub
> 2,新的dockerHub->阿里镜像服务

**Comment by lovitus** [comment]
非常感谢作者提供解答， 是我没明白json的应用哈，按提示修改后可以正常同步了。 新年快乐。
