### ISSUE TITLE
并发同步镜像遇到manifest blob unknown: blob unknown to registry报错

### ISSUE THREAD

**Issue by jokerhenson** [AliyunContainerService/image-syncer#7]
当我并发同步镜像时，会出现manifest blob unknown: blob unknown to registry的错误，我怀疑是镜像之间有共用层的情况下会出现。当我每次只同步一个镜像，且每次都把records清空，没有再遇到这样的问题。
是否有遇到类似的情况？

**Comment by hhyasdf** [comment]
> 当我并发同步镜像时，会出现manifest blob unknown: blob unknown to registry的错误，我怀疑是镜像之间有共用层的情况下会出现。当我每次只同步一个镜像，且每次都把records清空，没有再遇到这样的问题。
> 是否有遇到类似的情况？

出现manifest blob unknown: blob unknown to registry 的问题，表示manifest file在上传时，因为对应镜像的镜像层在此之前没有全部同步至目标registry而失败；records文件记录的是已同步的镜像层信息，请问是否是两个image-syncer程序在使用同一个records文件？

另外，能否尽可能详细描述你在同步执行的操作、命令以及现象？以便更好地定位问题，感谢～

**Comment by jokerhenson** [comment]
我的情况是这样的：
镜像仓库是本地搭的两个仓库；
同步配置文件内容如下：
```
{
    "auth": {
        "127.0.0.1:5000": {
            "username": "",
            "password": "",
            "insecure": true
        },
        "127.0.0.1:5001": {
            "username": "",
            "password": "",
            "insecure": true
        }
    },
    "images": {
        "127.0.0.1:5000/fire/busybox:latest": "127.0.0.1:5001/fire/busybox:latest",
        "127.0.0.1:5000/fire/centos:latest": "127.0.0.1:5001/fire/centos:latest",
        "127.0.0.1:5000/fire/docker:latest": "127.0.0.1:5001/fire/docker:latest",
        "127.0.0.1:5000/fire/golang:latest": "127.0.0.1:5001/fire/golang:latest",
        "127.0.0.1:5000/fire/haproxy:latest": "127.0.0.1:5001/fire/haproxy:latest",
        "127.0.0.1:5000/fire/helloworld:latest": "127.0.0.1:5001/fire/helloworld:latest",
        "127.0.0.1:5000/fire/httpd:latest": "127.0.0.1:5001/fire/httpd:latest",
        "127.0.0.1:5000/fire/java:latest": "127.0.0.1:5001/fire/java:latest",
        "127.0.0.1:5000/fire/jenkins:latest": "127.0.0.1:5001/fire/jenkins:latest",
        "127.0.0.1:5000/fire/kong:latest": "127.0.0.1:5001/fire/kong:latest",
        "127.0.0.1:5000/fire/maven:latest": "127.0.0.1:5001/fire/maven:latest",
        "127.0.0.1:5000/fire/mongo:latest": "127.0.0.1:5001/fire/mongo:latest",
        "127.0.0.1:5000/fire/nginx:latest": "127.0.0.1:5001/fire/nginx:latest",
        "127.0.0.1:5000/fire/php:latest": "127.0.0.1:5001/fire/php:latest",
        "127.0.0.1:5000/fire/postgres:latest": "127.0.0.1:5001/fire/postgres:latest",
        "127.0.0.1:5000/fire/python:2.7": "127.0.0.1:5001/fire/python:2.7",
        "127.0.0.1:5000/fire/rabbitmq:latest": "127.0.0.1:5001/fire/rabbitmq:latest",
        "127.0.0.1:5000/fire/ruby:latest": "127.0.0.1:5001/fire/ruby:latest",
        "127.0.0.1:5000/fire/tomcat:latest": "127.0.0.1:5001/fire/tomcat:latest",
        "127.0.0.1:5000/fire/ubuntu:latest": "127.0.0.1:5001/fire/ubuntu:latest"
   }
}
```
直接执行同步命令：image-syncer --config image-syncer.json；
这样就会遇到unknown blob的错误（操作前已删掉records）。

另外尝试的是每次json配置中只填一个镜像，命令相同，并且每次同步完都把records删掉，这样循环同步所有镜像可以成功。

**Comment by jokerhenson** [comment]
从日志上似乎没有明显的原因：
```
{"level":"info","msg":"Get manifest from 127.0.0.1:5000/fire/java:latest","time":"2019-11-17 16:02:38"}
{"level":"info","msg":"Get a blob sha256:7448db3b31eb523ef8dd3651601d4c2abad0d7a6a12b9c9e85f55ed9dad0ab8e(52472066) from 127.0.0.1:5000/fire/java:latest success","time":"2019-11-17 16:02:38"}
{"level":"info","msg":"Put blob sha256:cda54d6474c80093c7309946faf15645b38bdf22d20de6fe0e0220852bb4beb0(76651711) to 127.0.0.1:5001/fire/php:latest success","time":"2019-11-17 16:02:39"}
{"level":"info","msg":"Get a blob sha256:412447ed07294a264d7f4fb71175abe9b76fc28f692008d186ac04cd223a55e8(223) from 127.0.0.1:5000/fire/php:latest success","time":"2019-11-17 16:02:39"}
{"level":"info","msg":"Put blob sha256:1607093a898cc241de8712e4361dcd907898fff35b945adca42db3963f3827b3(10740168) to 127.0.0.1:5001/fire/jenkins:latest success","time":"2019-11-17 16:02:40"}
{"level":"info","msg":"Get a blob sha256:9a8ea045c9261c180a34df19cfc9bb3c3f28f29b279bf964ee801536e8244f2f(4336107) from 127.0.0.1:5000/fire/jenkins:latest success","time":"2019-11-17 16:02:40"}
{"level":"info","msg":"Put blob sha256:412447ed07294a264d7f4fb71175abe9b76fc28f692008d186ac04cd223a55e8(223) to 127.0.0.1:5001/fire/php:latest success","time":"2019-11-17 16:02:40"}
{"level":"info","msg":"Get a blob sha256:be73f2c7a50827a39b297b4c93015b3236ca5ead4498c5afbb2219b3fa89d8ea(12413936) from 127.0.0.1:5000/fire/php:latest success","time":"2019-11-17 16:02:40"}
{"level":"info","msg":"Put blob sha256:9a8ea045c9261c180a34df19cfc9bb3c3f28f29b279bf964ee801536e8244f2f(4336107) to 127.0.0.1:5001/fire/jenkins:latest success","time":"2019-11-17 16:02:41"}
{"level":"info","msg":"Get a blob sha256:d4eee24d4dacb41c21411e0477a741655303cdc48b18a948632c31f0f3a70bb8(50064642) from 127.0.0.1:5000/fire/jenkins:latest success","time":"2019-11-17 16:02:41"}
{"level":"info","msg":"Put blob sha256:667692510b7038b74e221f92eb33610e4968b669c8a718378ecb1f78739c3713(51769473) to 127.0.0.1:5001/fire/ruby:latest success","time":"2019-11-17 16:02:42"}
{"level":"info","msg":"Get a blob sha256:bed4ecf88e6a7ee9d32994c60892873ab8a3e199abdfbad73488537b1d3d52dd(192051442) from 127.0.0.1:5000/fire/ruby:latest success","time":"2019-11-17 16:02:42"}
{"level":"info","msg":"Put blob sha256:be73f2c7a50827a39b297b4c93015b3236ca5ead4498c5afbb2219b3fa89d8ea(12413936) to 127.0.0.1:5001/fire/php:latest success","time":"2019-11-17 16:02:43"}
{"level":"info","msg":"Get a blob sha256:ccea27a56d4607f701f33bf0b15799049bbeed09d5711448cd6fb932791b04fb(489) from 127.0.0.1:5000/fire/php:latest success","time":"2019-11-17 16:02:43"}
{"level":"info","msg":"Put blob sha256:ccea27a56d4607f701f33bf0b15799049bbeed09d5711448cd6fb932791b04fb(489) to 127.0.0.1:5001/fire/php:latest success","time":"2019-11-17 16:02:44"}
{"level":"info","msg":"Get a blob sha256:e652349e8aa043ca2ffc2550940e98a2182869a4352ae13fc349993c3990dada(28701101) from 127.0.0.1:5000/fire/php:latest success","time":"2019-11-17 16:02:44"}
{"level":"info","msg":"Put blob sha256:7448db3b31eb523ef8dd3651601d4c2abad0d7a6a12b9c9e85f55ed9dad0ab8e(52472066) to 127.0.0.1:5001/fire/java:latest success","time":"2019-11-17 16:02:50"}
{"level":"info","msg":"Get a blob sha256:c36604fa79391bd9451d544c5503da6b56125d5178f56b2b1559d02055b708d1(19192681) from 127.0.0.1:5000/fire/java:latest success","time":"2019-11-17 16:02:50"}
{"level":"info","msg":"Put blob sha256:e652349e8aa043ca2ffc2550940e98a2182869a4352ae13fc349993c3990dada(28701101) to 127.0.0.1:5001/fire/php:latest success","time":"2019-11-17 16:02:50"}
{"level":"info","msg":"Get a blob sha256:35d8aa4ba78303bbbbf164e31005b4445ed1e7dea91eb641d8d1f7bb40510e30(2202) from 127.0.0.1:5000/fire/php:latest success","time":"2019-11-17 16:02:50"}
{"level":"info","msg":"Put blob sha256:35d8aa4ba78303bbbbf164e31005b4445ed1e7dea91eb641d8d1f7bb40510e30(2202) to 127.0.0.1:5001/fire/php:latest success","time":"2019-11-17 16:02:51"}
{"level":"info","msg":"Get a blob sha256:dd9d93e7999db7b30616d8efc13e64949057b7eb106fba5d1e3553280c9e51e5(248) from 127.0.0.1:5000/fire/php:latest success","time":"2019-11-17 16:02:51"}
{"level":"info","msg":"Put blob sha256:dd9d93e7999db7b30616d8efc13e64949057b7eb106fba5d1e3553280c9e51e5(248) to 127.0.0.1:5001/fire/php:latest success","time":"2019-11-17 16:02:51"}
{"level":"info","msg":"Get a blob sha256:66f02e7e72bddcdd9aa2e121eb169c2634731413d3c8592deb87ba670f81c2e7(210) from 127.0.0.1:5000/fire/php:latest success","time":"2019-11-17 16:02:51"}
{"level":"info","msg":"Put blob sha256:66f02e7e72bddcdd9aa2e121eb169c2634731413d3c8592deb87ba670f81c2e7(210) to 127.0.0.1:5001/fire/php:latest success","time":"2019-11-17 16:02:51"}
{"level":"info","msg":"Get a blob sha256:0ceab3be41fbd8ae9f6abc6ae207ee28e0bd06bf73efe53c0f3f73dc7ee4c2d9(10090) from 127.0.0.1:5000/fire/php:latest success","time":"2019-11-17 16:02:51"}
{"level":"info","msg":"Put blob sha256:0ceab3be41fbd8ae9f6abc6ae207ee28e0bd06bf73efe53c0f3f73dc7ee4c2d9(10090) to 127.0.0.1:5001/fire/php:latest success","time":"2019-11-17 16:02:52"}
{"level":"error","msg":"Put manifest to 127.0.0.1:5001/fire/php:latest error: Error uploading manifest latest to 127.0.0.1:5001/fire/php: manifest blob unknown: blob unknown to registry","time":"2019-11-17 16:02:52"}
```
看起来每层是put成功的，但最后 put manifest会报错。

**Comment by hhyasdf** [comment]
@jokerhenson 日志输出看起来跟records文件没有关系，如果用到了records文件，应该会输出“Blob xxx has been pushed to xxxx according to records ...”的字样；

镜像之间共用镜像层的问题，由于看起来所有的层都被实际拉取并且成功push了，应该可以排除，初步怀疑跟镜像仓库本身的并发设置有关；

尝试下 image-syncer -p 1 --config image-syncer.json，将并发数改为1应该可以解决当前问题

**Comment by jokerhenson** [comment]
另外个问题想咨询下，如果是配有证书认证的仓库，是否需要在执行image-syncer工具的机器上也准备好对应证书？

**Comment by hhyasdf** [comment]
@jokerhenson 如果是自签证书的话，是的

**Comment by felix0080** [comment]
@hhyasdf 为什么不可以并发操作，是这个程序有bug，还是只能单线程下载呢

**Comment by hhyasdf** [comment]
@felix0080 可以并发操作的，我也用原生的docker registry尝试了下，在直接docker run registry的情况下确实会有这个问题，但是harbor以及类似dockerhub、ACR这种容器镜像服务是没有遇到这个问题的

现在问题定位到了：传输一个镜像的时候，最开始传的镜像层会被registry“丢失”，考虑应该是registry启动的config需要配置，但是还没找到解决方案

参考：https://docs.docker.com/registry/configuration/#uploadpurging

**Comment by malc0lm** [comment]
这个问题我也复现了，不过应该和仓库为没有关系，感觉应该是https://github.com/docker/distribution/issues/634 这个问题，跨仓库的blob复用应该使用Cross repository push，而不是就不去put这个blob了。

**Comment by malc0lm** [comment]
@hhyasdf 大佬看看 跪求增加这个机制  docker client 跨仓库复用blob会有mount from 字样

**Comment by hhyasdf** [comment]
> 这个问题我也复现了，不过应该和镜像仓库地址dockerhub或者acr或者自建没有关系，感觉应该是[docker/distribution#634](https://github.com/docker/distribution/issues/634) 这个问题，跨仓库的blob复用应该使用Cross repository push，而不是就不去put这个blob了。

请问下能否描述下准确的复现手段呢？BTW，本项目并没有使用 docker client 哈～

**Comment by huapox** [comment]
+1

**Comment by scxu** [comment]
我也遇到了同样的情况，虽然我有一个脚本可以复现这个报错，但这里面有 30+ 个镜像，所以也说不清楚具体是什么场景导致了这个失败。不过这 30+ 个镜像的特点是它们共享了很多层。我试图用两个简单的有共享层的镜像复现这个问题没有成功...

**Comment by scxu** [comment]
这个东西似乎确实有问题...我并发是 1 也照样子报错的，请问有什么进展吗...比如是 registry 的配置需要哪里做改动吗

**Comment by hhyasdf** [comment]
> 这个东西似乎确实有问题...我并发是 1 也照样子报错的，请问有什么进展吗...比如是 registry 的配置需要哪里做改动吗

目前我这边还没能找到复现方式，看起来是镜像以及镜像仓库行为的问题～

**Comment by liangyuanpeng** [comment]
是的，我也遇到了这个问题，
```
ERRO[2020-04-13 20:04:33] Put manifest to registry.cn-shenzhen.aliyuncs.com/lan-k8s/etcd:3.0.13-experimental.3 error: Error uploading manifest 3.0.13-experimental.3 to registry.cn-shenzhen.aliyuncs.com/lan-k8s/etcd: errors:
manifest blob unknown: blob unknown to registry
manifest blob unknown: blob unknown to registry
manifest blob unknown: blob unknown to registry
```

启动参数  
```
./image-syncer --proc=6 --config=./config.json
```

config.json
```
{
    "images": {

        "k8s.gcr.io/kube-proxy": "registry.cn-shenzhen.aliyuncs.com/lan-k8s/kube-proxy",
        "k8s.gcr.io/etcd" : "registry.cn-shenzhen.aliyuncs.com/lan-k8s/etcd"
    }    
}
```

**Comment by hhyasdf** [comment]
> 是的，我也遇到了这个问题，
> 
> ```
> ERRO[2020-04-13 20:04:33] Put manifest to registry.cn-shenzhen.aliyuncs.com/lan-k8s/etcd:3.0.13-experimental.3 error: Error uploading manifest 3.0.13-experimental.3 to registry.cn-shenzhen.aliyuncs.com/lan-k8s/etcd: errors:
> manifest blob unknown: blob unknown to registry
> manifest blob unknown: blob unknown to registry
> manifest blob unknown: blob unknown to registry
> ```
> 
> 启动参数
> 
> ```
> ./image-syncer --proc=6 --config=./config.json
> ```
> 
> config.json
> 
> ```
> {
>     "images": {
> 
>         "k8s.gcr.io/kube-proxy": "registry.cn-shenzhen.aliyuncs.com/lan-k8s/kube-proxy",
>         "k8s.gcr.io/etcd" : "registry.cn-shenzhen.aliyuncs.com/lan-k8s/etcd"
>     }    
> }
> ```

我使用相同的配置是可以成功的，麻烦确定下 blob 是不是都 put success 了没哈～，这个 issue 关注的是 “所有 blob 都 put 成功，但是 manifest 无法上传” 的问题

```
INFO[2020-04-14 13:10:05] Get manifest from k8s.gcr.io/etcd:3.0.13-experimental.3
INFO[2020-04-14 13:10:05] Blob sha256:56bec22e355981d8ba0878c6c2f23b21f422f30ab0aba188b54f1ffeff59c190(668151) has been pushed to registry.cn-shenzhen.aliyuncs.com according to records, will not be pulled
INFO[2020-04-14 13:10:05] Blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4(32) has been pushed to registry.cn-shenzhen.aliyuncs.com according to records, will not be pulled
INFO[2020-04-14 13:10:05] Blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4(32) has been pushed to registry.cn-shenzhen.aliyuncs.com according to records, will not be pulled
INFO[2020-04-14 13:10:05] Blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4(32) has been pushed to registry.cn-shenzhen.aliyuncs.com according to records, will not be pulled
INFO[2020-04-14 13:10:06] Get a blob sha256:00e00a5f7fc90b1c5d12228dafc355cf4bc5247da35187531e58a5613723b80a(37516084) from k8s.gcr.io/etcd:3.0.13-experimental.3 success
INFO[2020-04-14 13:11:18] Put blob sha256:00e00a5f7fc90b1c5d12228dafc355cf4bc5247da35187531e58a5613723b80a(37516084) to registry.cn-shenzhen.aliyuncs.com/ruohe/etcd:3.0.13-experimental.3 success
```

**Comment by zlseu-edu** [comment]
这个问题，我也遇到了。
```
INFO[2020-04-20 17:20:59] Get manifest from registry.cn-hangzhou.aliyuncs.com/tektoncd-pipeline-cmd/entrypoint:v0.9.2
INFO[2020-04-20 17:20:59] Blob sha256:322973677ef5fb0405c230fed304b2e907f46a1edb921bab269f88547bcf726f(760923) has been pushed to test-001-registry.cn-hangzhou.cr.aliyuncs.com according to records, will not be pulled
INFO[2020-04-20 17:20:59] Blob sha256:5d06f228fbd37710b8bd30ea8feff2b237f7d74c35fc7fed0135556cf86f1af8(10624478) has been pushed to test-001-registry.cn-hangzhou.cr.aliyuncs.com according to records, will not be pulled
INFO[2020-04-20 17:20:59] Blob sha256:67efcedf795d93201c10a0faf50e1ba9fe2c4af9df3ed853da47b968ecb80309(1333812) has been pushed to test-001-registry.cn-hangzhou.cr.aliyuncs.com according to records, will not be pulled
INFO[2020-04-20 17:20:59] Blob sha256:8c3f292b29e739cc083499537e6ef428196d3fb36d172bb0468e6404c8baf577(1353) has been pushed to test-001-registry.cn-hangzhou.cr.aliyuncs.com according to records, will not be pulled
ERRO[2020-04-20 17:20:59] Put manifest to test-001-registry.cn-hangzhou.cr.aliyuncs.com/tektoncd-pipeline-cmd/entrypoint:v0.9.2 error: Error uploading manifest v0.9.2 to test-001-registry.cn-hangzhou.cr.aliyuncs.com/tektoncd-pipeline-cmd/entrypoint: manifest blob unknown: blob unknown to registry
```

通过 charles 抓了一些 https 请求，看到在 PUT manifests 时候出错了，返回了 `400 Bad Request`。并且没有看到推送 blob 的请求。所以怀疑是镜像仓库中 manifests 指向的某些 blobs 不存在，所以 registry 报错了。

看了代码，发现 image-syncer 维护了一个 record 文件来记录 registry 下某个 blob 是否已存在，如果已存在，那么就不进行 push 了。
```
	// blob transformation
	for _, b := range blobInfos {
		if sizeInRecord, exist := SynchronizedBlobs.Query(t.destination.GetRegistry(), string(b.Digest)); !exist {
			// pull a blob from source
			blob, size, err := t.source.GetABlob(b)
			if err != nil {
				return t.Errorf("Get blob %s(%v) from %s/%s:%s failed: %v", b.Digest, size, t.source.GetRegistry(), t.source.GetRepository(), t.source.GetTag(), err)
			}
			t.Infof("Get a blob %s(%v) from %s/%s:%s success", b.Digest, size, t.source.GetRegistry(), t.source.GetRepository(), t.source.GetTag())

			b.Size = size
			// push a blob to destination
			if err := t.destination.PutABlob(blob, b); err != nil {
				return t.Errorf("Put blob %s(%v) to %s/%s:%s failed: %v", b.Digest, b.Size, t.destination.GetRegistry(), t.destination.GetRepository(), t.destination.GetTag(), err)
			}
			t.Infof("Put blob %s(%v) to %s/%s:%s success", b.Digest, b.Size, t.destination.GetRegistry(), t.destination.GetRepository(), t.destination.GetTag())

			if err := SynchronizedBlobs.Record(t.destination.GetRegistry(), string(b.Digest), size); err != nil {
				t.Infof("Record blobs error: %v, it will slow down you speed", err)
			}
		} else {
			// print the log of ignored blob
			t.Infof("Blob %s(%v) has been pushed to %s according to records, will not be pulled", b.Digest, sizeInRecord, t.destination.GetRegistry())
		}
	}
```


问题就出在这里：blob 如果是跨仓库的，那么还是需要进行 push 的，不能跳过。

所以 image-syncer 应该维护 repository 级别的 blob 记录。将记录转变为 repository 级别，再进行同步，就没有问题了。

**Comment by huapox** [comment]
syncer急着用，私下已解决了 还想着说提个PR 晚了一步， 顺带还是来个硬广：最近改的容器跳板机 https://github.com/infrastlabs/k8s-jumpserver 

K8S容器版跳板机，POD自注册，还原传统体验 方便开发调试及线上问题排查

**Comment by huapox** [comment]
看了下修复代码，重提了PR，原由如下：

- 第一句没毛病， 如前面@malc0lm所说 这是问题源头
> 问题就出在这里：blob 如果是跨仓库的，那么还是需要进行 push 的，不能跳过。

- 第二句，这里的处理思路不够优雅，一开始我也是这么干的。
> 所以 image-syncer 应该维护 repository 级别的 blob 记录。将记录转变为 repository 级别，再进行同步，就没有问题了。

直接把`if sizeInRecord, exist := SynchronizedBlobs.Query(t.destination.GetRegistry(), string(b.Digest)); !exist {`判断注释了，每次都推送即可

1.这样是可以保持，重推blob时不会有重复的，参看 https://github.com/containers/image/blob/v3.0.2/docker/docker_image_dest.go#L132 代码。

2.但是这样丢失了@hhyasdf对于records的全局复用机制，records细化到repo之后每次要重复pullBlobs，导致不必要的源头拉取blog带宽占用及时耗！

- 更优处理方式

`containers/image`其实已经有相关API了，我们再原有records基础之上，在else的判断中再调用下`TryReusingBlob`即可轻松搞定。详见如上PR #35

**Comment by zlseu-edu** [comment]
> 看了下修复代码，重提了PR，原由如下：
> 
> **一、问题分析**
> 
> 没毛病， 如前面@malc0lm所说 这是问题源头
> 
> > 问题就出在这里：blob 如果是跨仓库的，那么还是需要进行 push 的，不能跳过。
> 
> **二、原处理思路分析**
> 
> 这里的处理思路不够优雅，一开始我也是这么干的。
> 
> > 所以 image-syncer 应该维护 repository 级别的 blob 记录。将记录转变为 repository 级别，再进行同步，就没有问题了。
> 
> 直接把`if sizeInRecord, exist := SynchronizedBlobs.Query(t.destination.GetRegistry(), string(b.Digest)); !exist {`判断注释了，每次都推送即可
> 
> * 1. 这样是可以保持重推blob时不会有重复的，参看 https://github.com/containers/image/blob/v3.0.2/docker/docker_image_dest.go#L132 代码。
> * 1. 但是这样丢失了@hhyasdf对于records的全局复用机制，records细化到repo之后每次要重复pullBlobs，导致不必要的源头拉取blog带宽占用及时耗！
> 
> **三、更优处理方式**
> 
> `containers/image`其实已经有相关API了，我们再原有records基础之上，在else的判断中再调用下`TryReusingBlob`即可轻松搞定。详见如上PR #35

reuse 方式看起来更优雅。

**Comment by hhyasdf** [comment]
> 看了下修复代码，重提了PR，原由如下：
> 
> **一、问题分析**
> 
> > 问题就出在这里：blob 如果是跨仓库的，那么还是需要进行 push 的，不能跳过。
> 
> 没毛病， 如前面@malc0lm所说 这是问题源头
> 
> **二、原处理思路分析**
> 
> > 所以 image-syncer 应该维护 repository 级别的 blob 记录。将记录转变为 repository 级别，再进行同步，就没有问题了。
> 
> 这里的处理思路不够优雅，一开始我也是这么干的。
> 
> 简单粗爆，直接把`if sizeInRecord, exist := SynchronizedBlobs.Query(t.destination.GetRegistry(), string(b.Digest)); !exist {`判断注释了，每次都推送即可成功
> 
> * 1. 这样做是可以保证重推blob时不重复push的，参看`containers/image`项目 `PutBlob`API代码 https://github.com/containers/image/blob/v3.0.2/docker/docker_image_dest.go#L132 。
> * 1. 但是这样丢失了@hhyasdf对于records的全局pull复用机制，records细化到repo之后每次要重复pullBlobs，导致不必要的源头拉取blog带宽占用及时耗！
> 
> **三、更优处理方式**
> 
> `containers/image`其实已经有相关API了，我们再原有records基础之上，在else的判断中再调用下`TryReusingBlob`即可轻松搞定。详见如上PR #35
> 
> **四、写在最后**
> 
> 感谢`containers/image`的存在及@hhyasdf对`image-syncer`工具的良好封装，提个小建议：`是否考虑对master做下rebase把vendor清理一下`

非常感谢，很棒的建议和 pr。借此机会，我理解我们是否能从 image-syncer 中移除 records 的机制，直接使用 `TryReusingBlob` 作为判断 blob 是否已经传输的依据？这样可以完全不依赖 records 文件记录已经传输过的blob信息，避免带来一些使用上的困扰。

cc/ @zlseu-edu

**Comment by huapox** [comment]
> 借此机会，我理解我们是否能从 image-syncer 中移除 records 的机制，直接使用 `TryReusingBlob` 作为判断 blob 是否已经传输的依据？

一、**建议1**:保留records 机制在内存级别，以在批量sync时保持它的blobPull判断机制 本身retry重试也是需要记录文件的。(如果有更好方法缓存这类blobPull记录的话 另说)

> 这样可以完全不依赖 records 文件记录已经传输过的blob信息，避免带来一些使用上的困扰。

二、这里要分析一下需求 `避免带来一些使用上的困扰`

用户使用syncer有多种场景：

- 1.长时运行跑sync，设定好固定的同步清单。如sync A> B
- 2.按次跑sync，变动的同步清单。如sync A> B， 清单1 清单2 清单3...
- 3.按次跑sync，多次同源 同步到多个目标仓库。如A> B， A> C。
- 4.多实例并行跑syncer。

如上，结合你提到的，`使用上的困扰的困扰`是否可以这么理解，如下就是一种情况：比如先同步 A>B， 接着同步相同清单A>C 这时问题来了： syncer告诉你全同步过了..

**建议2**: 可以搞一个flag参数项， 默认不输出到磁盘文件， 但支持用户通过该flag自定义输出文件名。 路径同时支持相对/绝对路径

**Comment by hhyasdf** [comment]
> > 借此机会，我理解我们是否能从 image-syncer 中移除 records 的机制，直接使用 `TryReusingBlob` 作为判断 blob 是否已经传输的依据？
> 
> @hhyasdf 感谢回复~
> 
> 一、**建议1**:保留records 机制在内存级别，以在批量sync时保持它的blobPull判断机制 本身retry重试也是需要记录信息的。(如果有更好方法缓存这类blobPull记录的话 另说)
> 
> 二、这里要分析一下需求 `避免带来一些使用上的困扰`
> 
> > 这样可以完全不依赖 records 文件记录已经传输过的blob信息，避免带来一些使用上的困扰。
> 
> 用户使用syncer有多种场景：
> 
> * 1.长时运行跑sync，设定好固定的同步清单。如sync A> B
> * 2.按次跑sync，变动的同步清单。如sync A> B， 清单1 清单2 清单3...
> * 3.按次跑sync，多次同源 同步到多个目标仓库。如A> B， A> C。
> * 4.多实例并行跑syncer。
> 
> 如上，结合你提到的，`使用上的困扰的困扰`是否可以这么理解，如下就是一种情况：比如先同步 A>B， 接着同步相同清单A>C 这时问题来了： syncer告诉你全同步过了..
> 
> **建议2**: 可以搞一个flag参数项， 默认不输出到磁盘文件， 但支持用户通过该flag自定义输出文件名。 路径同时支持相对/绝对路径

嗯嗯，使用上的困扰和你想的一样，用户可能会在同一路径下多次使用image-syncer，这个是 records file 带来的一个问题。

我的想法是在每次 blob pull 之前，先用 TryReusingBlob 判断目标 registry 中对应的 blob 是否存在，如果不存在才进行 pull/push 操作，这样可以极大提高程序的鲁棒性，性能上，只会增加一次网络io，看了下源码由于这个请求比较简单，不会消耗太多时间。

参见 #36

**Comment by huapox** [comment]
> 我的想法是在每次 blob pull 之前，先用 TryReusingBlob 判断目标 registry 中对应的 blob 是否存在，如果不存在才进行 pull/push 操作，这样可以极大提高程序的鲁棒性，性能上，只会增加一次网络io，看了下源码由于这个请求比较简单，不会消耗太多时间。

LGTM!

**Comment by hhyasdf** [comment]
这个问题已在 v1.1.0 的 image-syncer 中修复，感谢各位的使用和帮助～，这个 issue 先关闭了，有问题依旧可以在下面评论。
