### ISSUE TITLE
增加配置选项只同步指定架构的镜像

### ISSUE THREAD

**Issue by whypro** [AliyunContainerService/image-syncer#74]
目前对于多架构的镜像，比如 `quay.io/prometheus/prometheus:v2.25.2` 支持下面几个架构：
```
linux/ppc64le
linux/amd64
linux/arm64
linux/arm
linux/s390x
```
image-syncer 会将所有的架构同步过去，这对大部分场景都是没有必要的，是否可以提供相应的命令行参数或 config 选项来限定镜像架构（比如只同步常用的 `linux/amd64`）？

**Comment by hhyasdf** [comment]
想确定下这个功能主要面向的场景是？生产环境中是否有这样的场景？

**Comment by whypro** [comment]
我们生产环境为了降低镜像的拉取时间，会将外网镜像同步至内网。但由于存储、带宽等资源的限制，如果同步全部架构的镜像，耗时会比较长，且除了 linux/amd64 之外的镜像生产环境是用不到的，也会浪费一些存储空间。
