### ISSUE TITLE
希望支持镜像架构过滤，比如arm64，amd64

### ISSUE THREAD

**Issue by cqhaohao** [AliyunContainerService/image-syncer#86]
Type: *feature request*

### 希望支持镜像架构过滤，比如arm64，amd64

docker manifest 提供了 构建镜像的操作系统和体系结构，希望镜像同步时可以根据architecture 选择同步的镜像

比如 redis，docker官方提供了amd64，arm64等版本，他们的版本号是一样的（redis:latest）,有时我们只希望同步amd64的版本，希望能支持架构过滤功能。

**Comment by hhyasdf** [comment]
v1.3.1 版本通过 --arch 的参数已经支持

**Comment by cqhaohao** [comment]
tks
