### ISSUE TITLE
拆解image-syncer

### ISSUE THREAD

**Issue by ly-wjj** [AliyunContainerService/image-syncer#88]
使用image-syncer同步镜像，同步效率大大提升，使用起来也很方便。对此我对该工具进行了拆解。拆解原文：https://mp.weixin.qq.com/s/YXBpENLmxMnhh2GmInMLXw 
希望能够帮助到，对于想了解image-syncer原理的同学。

**Comment by hhyasdf** [comment]
Thanks, but it's not an issue.
