### ISSUE TITLE
一个原镜像同步多个目标库 yaml 写法

### ISSUE THREAD

**Issue by ChangJinLong** [AliyunContainerService/image-syncer#95]
quay.io/coreos/kube-rbac-proxy:
      \- quay.io/ruohe/kube-rbac-proxy01
      \- quay.io/ruohe/kube-rbac-proxy02

**Comment by hhyasdf** [comment]
v1.5.1 版本支持了这个功能:

quay.io/coreos/kube-rbac-proxy:v1.1:
  - quay.io/ruohe/kube-rbac-proxy1
  - quay.io/ruohe/kube-rbac-proxy2
